### PR TITLE
Fix obscured gemfile issue

### LINKED ISSUE #891: Running with docker image does not work out-of-the-box
### Before submitting an issue, please be sure to

- [x] Read [the contributing instructions](https://github.com/github/pages-gem/blob/master/docs/CONTRIBUTING.md#contributing-to-the-github-pages-gem)
- [ ] Update to the latest Gem version (run `bundle update github-pages`) (does not apply)

### This issue affects

- [ ] The site generated by GitHub Pages
- [x] Building sites locally

### What did you do (e.g., steps to reproduce)

Attempting to use the github-pages gem using the docker image with the instructions from the README does not work out-of-the-box, for example:

```sh
git clone https://github.com/github/pages-gem
cd pages-gem
git checkout v228
docker build -t gh-pages .
cd ..
git clone https://github.com/github/personal-website
cd personal-website
docker run --rm -it -p 4000:4000 -v ${PWD}:/src/site gh-pages
```

### What did you expect to happen?

To be able to run the site locally at localhost:4000

### What happened instead?

I got the following error:

```sh
Traceback (most recent call last):
        17: from /usr/local/bundle/bin/jekyll:25:in `<main>'
        16: from /usr/local/bundle/bin/jekyll:25:in `load'
        15: from /usr/local/bundle/gems/jekyll-3.9.3/exe/jekyll:11:in `<top (required)>'
        14: from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/plugin_manager.rb:50:in `require_from_bundler'
        13: from /usr/local/lib/ruby/site_ruby/2.7.0/bundler.rb:162:in `setup'
        12: from /usr/local/lib/ruby/site_ruby/2.7.0/bundler/runtime.rb:18:in `setup'
        11: from /usr/local/lib/ruby/site_ruby/2.7.0/bundler/definition.rb:266:in `specs_for'
        10: from /usr/local/lib/ruby/site_ruby/2.7.0/bundler/definition.rb:200:in `specs'
         9: from /usr/local/lib/ruby/site_ruby/2.7.0/bundler/definition.rb:523:in `materialize'
         8: from /usr/local/lib/ruby/site_ruby/2.7.0/bundler/definition.rb:301:in `resolve'
         7: from /usr/local/lib/ruby/site_ruby/2.7.0/bundler/definition.rb:570:in `start_resolution'
         6: from /usr/local/lib/ruby/site_ruby/2.7.0/bundler/resolver.rb:28:in `start'
         5: from /usr/local/lib/ruby/site_ruby/2.7.0/bundler/resolver.rb:61:in `setup_solver'
         4: from /usr/local/lib/ruby/site_ruby/2.7.0/bundler/resolver.rb:357:in `prepare_dependencies'
         3: from /usr/local/lib/ruby/site_ruby/2.7.0/bundler/resolver.rb:357:in `map'
         2: from /usr/local/lib/ruby/site_ruby/2.7.0/bundler/resolver.rb:357:in `each'
         1: from /usr/local/lib/ruby/site_ruby/2.7.0/bundler/resolver.rb:372:in `block in prepare_dependencies'
/usr/local/lib/ruby/site_ruby/2.7.0/bundler/resolver.rb:312:in `raise_not_found!': Could not find gem 'github-pages' in locally installed gems. (Bundler::GemNotFound)
```

### Additional information

The only way I could get it working was by running `bundle install` before `jekyll serve`:

```sh
docker run --rm -it \
    -p 4000:4000 \
    -v ${PWD}:/src/site \
    gh-pages \
    sh -c "bundle install && jekyll serve -H 0.0.0.0 -P 4000"
```

Shouldn't the github-pages gem be already preinstalled in the docker image?

### PR DESCRIPTION
**Pull request by mrmanc**
(edited to include just one change per [@parkr’s suggestion](https://github.com/github/pages-gem/pull/912#issuecomment-2004587675)—see also stacked PR #914)

Fixes #891. `jekyll` was unable to find the gems which Bundler had installed as part of the `Dockerfile` because it was finding a `Gemfile` in the currently working directory (`/src/site`), which belongs to the site being built. I resolved this by setting an environment variable to tell Bundler where to find the correct `Gemfile`.

I’m not a Ruby developer, so I might not have done this conventionally. However it seems to work, and it was the minimum change I could make to resolve those issues.

### CODE REVIEW

**Comment by mrmanc** [comment]
Is there anything else that the team need to support this change? Please let me know if there’s anything else I can do to get it merged.

File: lib/github-pages/dependencies.rb [hunk 1]
```diff
@@ -9,6 +9,7 @@ class Dependencies
       # Jekyll
       "jekyll" => "3.9.5",
       "jekyll-sass-converter" => "1.5.2",
+      "webrick" => "1.8.1",
```
Comment (parkr) [inline lib/github-pages/dependencies.rb:12]: Now that everything is upgraded to Ruby 3, I'd recommend this for sure 👍

**Review by parkr — APPROVED** [review]

**Comment by parkr** [comment]
I might recommend separating the addition of the webrick and the modification of the docket files into two separate PRs. Otherwise LGTM.

**Comment by mrmanc** [comment]
> I might recommend separating the addition of the webrick and the modification of the docket files into two separate PRs. Otherwise LGTM.

Thanks—I’ve done as you’ve suggested 😃. I’m guessing you aren’t able to act on this yourself?

**Review by parkr — APPROVED** [review]

**Review by yoannchaudet — APPROVED** [review]
